### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SimSel02** [namanArora1022/rubiks-cube-scramble-generator#1]
I tried to use the API it does not work ATM.
Is it still available?

**Comment by naman22a** [comment]
My railway api plan was expired 😅
here is the new link, i also updated it on the website
[https://rubiks-cube-scramble-generator.onrender.com/api?puzzleType=3x3](https://rubiks-cube-scramble-generator.onrender.com/api?puzzleType=3x3)

**Comment by SimSel02** [comment]
Thanks so much!

**Comment by naman22a** [comment]
Your welcome
